export const DATA_MOCK = [
  {
    id: 1,
    firstName: 'Santiago',
    lastName: 'Gigli',
    fidelity: 100,
  },
  {
    id: 2,
    firstName: 'Julian',
    lastName: 'Vicente',
    fidelity: 100,
  },
  {
    id: 3,
    firstName: 'Nicolas',
    lastName: 'Viola',
    fidelity: 100,
  },
  {
    id: 4,
    firstName: 'Aquiles',
    lastName: 'Mariani',
    fidelity: 100,
  },
  {
    id: 5,
    firstName: 'Martin',
    lastName: 'Raveglia',
    fidelity: 100,
  },
  {
    id: 6,
    firstName: 'Nicolas',
    lastName: 'Cagnina',
    fidelity: 100,
  },
  {
    id: 7,
    firstName: 'Lucas',
    lastName: 'Malvasia',
    fidelity: 100,
  },
  {
    id: 8,
    firstName: 'Alejandro',
    lastName: 'Lupo',
    fidelity: 100,
  },
  {
    id: 9,
    firstName: 'Diego',
    lastName: 'Castro',
    fidelity: 100,
  },
  {
    id: 10,
    firstName: 'Julian',
    lastName: 'Cedaro',
    fidelity: 100,
  },
  {
    id: 11,
    firstName: 'Naila',
    lastName: 'Ghigo',
    fidelity: 100,
  },
  {
    id: 12,
    firstName: 'Nicolas',
    lastName: 'Blascow',
    fidelity: 100,
  },
  {
    id: 13,
    firstName: 'Agustin',
    lastName: 'Schiaffino',
    fidelity: 100,
  },
  {
    id: 14,
    firstName: 'Facundo',
    lastName: 'De Lafuente',
    fidelity: 100,
  },
  {
    id: 15,
    firstName: 'Rodrigo',
    lastName: 'Sibrins',
    fidelity: 100,
  },
];
