export enum Routes {
  LOG_IN = 'LOG_IN',
  CREATE_ACCOUNT = 'CREATE_ACCOUNT',
  HOME = 'HOME',
  SELECT_PLAYERS = 'SELECT_PLAYERS',
  MATCH = 'MATCH',
  HISTORY = 'HISTORY',
  PROFILE = 'PROFILE',
}
